openapi: 3.0.0
info:
  title: Prompt Processing API
  version: v1
  contact:
    name: John Doe
    url: https://example.com
    
paths:
  /prompt:
    post:
      summary: Process a user prompt
      description: The request body should contain the user prompt in plain text. The
        request header should contain the backend ID and JWT authentication
        token.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: The user prompt.
      parameters:
        - in: header
          name: Backend-ID
          schema:
            type: string
          required: true
          description: The ID of the backend system.
      responses:
        '200':
          description: Prompt received and processed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string   

                    example: Prompt   
 received and processed
        '400':
          description: Bad Request - Missing prompt or Backend-ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Missing prompt in payload
        '401':
          description: Unauthorized - Missing or invalid JWT.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Missing Authorization header

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
